name: CI

on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test
        env:
          CI: true
